### ISSUE TITLE
Ctrl-C did not quit worker processes

### ISSUE THREAD

**Issue by wmertens** [avoidwork/tiny-worker#14]
Node v7.7.1
tiny-worker@2.0.1

I start workers as per the documentation, and they start repeating tasks via `setInterval()`. Then I quit the server using ctrl-c, and the workers do not quit.

Am I missing an event handler somewhere?

**Comment by avoidwork** [comment]
Hi,

Your problem is related to your choice of modules and the way you've written the code. An interval inside a child_ps will be killed if the parent is killed, but it sounds like ctrl-c / sigterm is being mishandled.

You could explicitly clean up the ps via:

```
process.on('SIGTERM', () => {
  worker.terminate(); // kill them all
  process.exit(0);
});
```

... but I don't think this solves the underlying issue you have. for ctx, I can't recreate this problem with just tiny-worker (in root of code):

#### sample script
```
var path = require("path"),
	Worker = require(path.join(__dirname, "lib", "index.js")),
	worker = new Worker(path.join(__dirname, "sample_worker.js"));

console.log("Created worker");
```

#### sample worker script
```
setInterval(function () {
	console.log("still going");
}, 1000);

onmessage = function (ev) {
	postMessage(ev.data);
};
```

#### console output
```
jason@blacky:~/Projects/tiny-worker (master)$ node sample.js 
Created worker
still going
still going
still going
still going
^C
jason@blacky:~/Projects/tiny-worker (master)$
```

**Comment by avoidwork** [comment]
I recreated the problem; not sure if this is accurate for your situation*

#### sample script with shutdown
```
var path = require("path"),
	Worker = require(path.join(__dirname, "lib", "index.js")),
	worker = new Worker(path.join(__dirname, "sample_worker.js"));

console.log("Created worker");

setTimeout(function () {
	process.exit(0);
});
```

Using the same worker script with timer...

#### console output
```
jason@blacky:~/Projects/tiny-worker (master)$ node sample_worker.js 
still going
still going
still going
still going
```

#### other console output
```
jason@blacky:~/Projects/tiny-worker (master)$ ps aux | grep node
root               93   1.5  0.0  2469688    436   ??  Ss    1Feb17  13:02.87 /System/Library/CoreServices/ionodecache -k /var/db/ionodecache.json
jason           33592   0.0  0.0  2440996    792 s002  S+    7:05am   0:00.00 grep node
jason           33408   0.0  0.3  3032860  21456 s000  S     7:05am   0:00.09 /Users/jason/.nvm/versions/node/v7.6.0/bin/node /Users/jason/Projects/tiny-worker/lib/worker.js
jason@blacky:~/Projects/tiny-worker (master)$ 
```

^ core quit on shortly after next tick (setTimeout is not process.nextTick), child ps lives on. you have something like this happening. since the parent ps has quit there's nothing listening/handling a sigterm or way to msg the child ps now, so it just lives on.

![screen shot 2017-04-10 at 7 09 27 am](https://cloud.githubusercontent.com/assets/369698/24859032/c8c42f26-1dbc-11e7-9e97-9ec5389a33c8.png)

new lines / spaces are me hitting 'ctrl-c'

**Comment by avoidwork** [comment]
Generally, keep a registry of your child ps and explicitly clean them up or you'll potentially have orphans.

**Comment by wmertens** [comment]
Wow, for someone with the nick `avoidwork` you sure dug deep! :) Thank you very much, I will do so. Perhaps the Readme should say something to that effect?

**Comment by avoidwork** [comment]
That's a problem domain I don't own. tiny-worker makes child_process easier, but I'm not providing support for core apis of node. You really need to go to nodejs.org and read about how the stuff works.

child_process & cluster have similar management issues.

**Comment by avoidwork** [comment]
@wmertens I will make a node on the README for people; I realize this is really 'out of band' info that's gathered when required, and not really sought out.

**Comment by wmertens** [comment]
Understood, but you *are* abstracting away `child_process`, so simply mentioning that would be helpful to future devs, no? In any case, your proposed solution with the sigterm handler worked fine. Thanks again!

**Comment by avoidwork** [comment]
@wmertens check https://github.com/avoidwork/tiny-worker#faq ... feel free to open a PR for edits/additions to that spot of the README. I have too many years experience now to grok what would be valuable there.

**Comment by avoidwork** [comment]
@wmertens just to make it interesting, if you're potentially running on windows use `SIGINT`. I've updated the FAQ of the README.

**Comment by wmertens** [comment]
💯 perfect!
