### ISSUE TITLE
Exception not thrown when worker file does not exist

### ISSUE THREAD

**Issue by zachbwh** [avoidwork/tiny-worker#32]
Basically the title, would be good if there was a check to see if the worker file doesn't exist.

**Comment by avoidwork** [comment]
Why would that be the lib's responsibility? Code your stuff better and that won't be possible.

**Comment by zachbwh** [comment]
Of course you could argue that but this is a fairly trivial fix which has the potential to be fixed in this one place potentially saving many users of this library a significant amount of time. It's definitely an unreasonable assumption to think that nobody makes mistakes in their code from time to time anyways.

I don't mean to come across as ungrateful for the work you have already done by the way, I'm just trying to understand where you are coming from.
I presume you made this library to help make other peoples lives easier right?

If I make a small pull request with this small addition would you please review and merge it?

Cheers

**Comment by avoidwork** [comment]
The issue is not related to the level of effort to implement the 'ask', it's that the 'ask' doesn't align with the project's goal of providing a drop-in replacement of a Web Worker; they don't throw like that.

![2019-05-21](https://user-images.githubusercontent.com/369698/58091019-95cc0f00-7b96-11e9-894b-aeb3c0db0ccf.png)

Contrasting opinion; it shouldn't be verifying the inputs. No lib should be verifying the inputs like this.

You're effectively asking something to take action on something else that you can't guarantee; you wouldn't do that in real life; it's actually against the nature of survival (wasting energy).
